rails_tut: "https://www.railstutorial.org/"
rails_tut_help: "https://www.railstutorial.org/help"
learn_enough: "https://www.learnenough.com/"
screencasts: "https://screencasts.railstutorial.org/"
rails_tut_book: "https://www.railstutorial.org/book"
